forfudan/decimojo

decimojo/decimal.mojo
tests/test_decimal_arithmetics.mojo

This implements `__truediv__` method.
Special attention was given to the division operation which properly handles:
- Different scales between dividend and divisor
- Exact vs. inexact divisions
- Correct decimal point placement
- Rounding according to specified modes
- Edge cases (zero dividend, identical numbers, scale limitations)
```mojo
var a = Decimal("12.34")
var b = Decimal("-2.0")
var result = a / b  # Returns -6.17 with proper scale handling
var c = Decimal("10.00")
var d = Decimal("2.00")
var result2 = c / d  # Returns 5 (no trailing zeros)
var e = Decimal("10.0")
var f = Decimal("3.0")
var result3 = e / f  # Returns 3.3333333333333333333333333333
```
This also fixes a bug in `__add__` when the values are just negative of each other.

[decimal] Implement `__truediv__` + fix bug in `__add__`

---

.github/workflows/test_pre_commit.yaml
.pre-commit-config.yaml
decimojo/__init__.mojo
decimojo/decimal.mojo
decimojo/mathematics.mojo
tests/test_decimal_arithmetics.mojo
tests/test_decimal_mathematics.mojo
tests/test_string_based_operations.mojo

This PR:
- Adds the `sqrt()` function.
- Add string-based addition and subtraction. Fix bugs in various extreme cases of arithmetic.
- Fix problems in add, sub, mul, and div.
- Add many tests for the functions and methods to ensure they work as expected.

[decimal][routines] Implement `sqrt()` + much debugging work

---

.gitignore
README.md
benches/bench.mojo
benches/bench_add.mojo
benches/bench_divide.mojo
benches/bench_multiply.mojo
benches/bench_subtract.mojo
decimojo/decimal.mojo
decimojo/maths/arithmetics.mojo
mojoproject.toml

This PR changes the return type of `coefficient()` from `String` to `UInt128` because Mojo now supports `UInt128` type in the nightly version.
Fix other functions for this change.
Renew some functions to get significant digits of coefficients by using `UInt128` instead of `String`.
Renew the `__float__` and `__int__` methods.
This PR introduces a comprehensive benchmarking suite for the `DeciMojo` library, comparing its performance with Python's `decimal` module. The changes include adding new benchmark scripts for various arithmetic operations and updating the documentation to guide users on running these benchmarks.
* Added a new section in `README.md` to explain how to run tests and benchmarks using the `magic` command.

[decimal][bench] change return type of `coefficient()` to UInt128 + add benches

---

mojoproject.toml
src/decimojo/utility.mojo
tests/test_arithmetics.mojo
tests/test_utility.mojo

This pull request includes multiple changes to the `mojoproject.toml` configuration file, the `src/decimojo/utility.mojo` source file, and the addition of new test cases in the `tests` directory. The most important changes include adding new utility functions, enhancing existing functions, and creating comprehensive test cases for these utilities.
* Added a new command `delete_package` to remove package files from the `tests` folder and integrated it into the `test` command in `mojoproject.toml`.
* Introduced the `bitcast` function to perform a direct memory bit copy from a `Decimal` type to a Mojo scalar type, ensuring efficient type casting without bit manipulation.
* Improved the `truncate_to_max` function with additional checks and optimizations for handling values that require …

[decimal] Add `bit_cast()` and fix `truncate_to_max()`

---

src/decimojo/decimal.mojo

This pull request includes a significant improvement to the `coefficient` method in the `Decimal` struct within the `src/decimojo/decimal.mojo` file. The changes aim to enhance performance by using a faster bitcast implementation.
* Updated the method documentation to include code formatting for better readability.
* Implemented a fast version of the `coefficient` method using `bitcast` to directly convert the three 32-bit parts to a `UInt128`, given little-endian memory order.
* Commented out the previous arithmetic implementation of combining the three 32-bit parts into a single `Int128`, retaining it as an alternative.

[decimojo] Use `bitcast()` for `coefficient()`

---

mojoproject.toml
src/decimojo/decimal.mojo
src/decimojo/maths/arithmetics.mojo
src/decimojo/maths/rounding.mojo
src/decimojo/utility.mojo
tests/test_utility.mojo

This pull request includes several changes in the `decimojo` project, focusing on enhancing the `multiply()` function with `UInt128` and `UInt256`. The performance of multiplication is significantly improved.
Enhancements to `Decimal` struct:
* [`src/decimojo/decimal.mojo`](diffhunk://#diff-c2178e6e0bbbbb0d3379f1513412224309d1232c444654e77abb5ce36b3a854fL879-R879): Added `raises` keyword to `__mul__` methods and introduced new methods `is_uint32able` and `is_uint64able` to check if the coefficient can be represented as `UInt32` or `UInt64` values. [[1]](diffhunk://#diff-c2178e6e0bbbbb0d3379f1513412224309d1232c444654e77abb5ce36b3a854fL879-R879) [[2]](diffhunk://#diff-c2178e6e0bbbbb0d3379f1513412224309d1232c444654e77abb5ce36b3a854fL889-R889) …

[decimal] Optimize `multiply()` with `UInt128` and `UInt256`

---

README.md
benches/bench_add.mojo
benches/bench_divide.mojo
benches/bench_multiply.mojo
benches/bench_subtract.mojo
mojoproject.toml
src/decimojo/maths/arithmetics.mojo
tests/test_arithmetics.mojo
tests/test_conversions.mojo
tests/test_creation.mojo
tests/test_division.mojo
tests/test_logic.mojo
tests/test_sqrt.mojo

This PR focuses on optimizing `divide()` by replacing string-based approach with int-based approach. It significantly improves the performance of `divide()` by from x100 to x10000 times.
1. **Advanced Overflow Prevention** - Precise coefficient bounds checking with proper truncation to maintain accurate results within the 96-bit limitation, particularly in division operations
2. **Comprehensive Edge Case Handling** - Special case optimizations for common scenarios (zero values, powers of 10, coefficient of 1) with proper error messages for impossible operations
3. **Sophisticated Scale Management** - Intelligent adjustment of decimal scales during arithmetic operations, preserving maximum precision while preventing overflow
4. **Performance Optimization** - Efficient binary exponentiation …

[decimal] Optimize `divide()` and replace string-based approach with int-based approach

---

mojoproject.toml
src/decimojo/decimal.mojo
src/decimojo/utility.mojo
tests/test_from_string.mojo

This pull request:
- Re-writes Decimal constructor from String via the static method `from_string()`. This significantly improves the performance (x100) and can handle different errors.
- Fixes a bug in the `round_to_keep_first_n_digits` function which may falsely round-up in round-half-to-even mode. This is caused by an implicit type conversion which makes the value unsigned.
- Adds comprehensive tests for the `Decimal.from_string()` method.
- Adds benchmarking tests for the `Decimal.from_string()` method.
* Use a more sophisticated approach to scan characters in the string.
* Can handle different mistakes and raise corresponding error messages.
* This significantly improves the performance (x100).
* Add a static method `from_string()`. Then `__init__` calls this method.
* Modified the …

[decimal] Re-write `from_string()` constructor and improve the performance

---

src/decimojo/utility.mojo

This pull request introduces a module-level cache for powers of 10 in the `src/decimojo/utility.mojo` file. The cache is designed to store the powers of 10 up to the required value, avoiding the need to recalculate the same powers multiple times. The cache is initialized with the first value (10^0 = 1) and extended as needed.
Key changes include:
* **Module-level cache initialization:**
* Added `var _power_of_10_as_uint128_cache` and `var _power_of_10_as_uint256_cache` to store cached values of powers of 10 for `UInt128` and `UInt256` types, respectively.
* Introduced `_init_power_of_10_as_uint128_cache` and `_init_power_of_10_as_uint256_cache` functions to initialize the caches with the first value (10^0 = 1).
* **Cache usage and extension:**
* Added `power_of_10_as_uint128` and …

[decimal] Add cache for powers of 10

---

src/decimojo/decimal.mojo
src/decimojo/maths/exp.mojo
src/decimojo/maths/rounding.mojo

This pull request includes significant refactoring and improvements to the `Decimal` struct in the `decimojo` library. The main changes involve simplifying the initialization of `Decimal` objects and adding a new method for creating `Decimal` instances from `UInt128` values.
Initialization Refactoring:
* Simplified the initialization logic by removing redundant constructors and consolidating the initialization process for `Int` and `UInt128` values.
New Method for `UInt128` Initialization:
* Added a new static method `from_uint128` to initialize a `Decimal` from a `UInt128` value, including validation for the value and scale.
Code Simplification:
* Updated existing methods to use the new `from_uint128` method for creating `Decimal` instances from `UInt128` values.
* Modified the `sqrt` …

[decimal] simplifying initialization of `Decimal` and add `from_uint128()`

---

README.md
docs/readme_zht.md
src/decimojo/__init__.mojo
src/decimojo/arithmetics.mojo
src/decimojo/comparison.mojo
src/decimojo/decimal.mojo
src/decimojo/exponential.mojo
src/decimojo/prelude.mojo
src/decimojo/rounding.mojo
src/decimojo/rounding_mode.mojo
src/decimojo/special.mojo
src/decimojo/utility.mojo

This pull request includes several changes to update the GitHub repository URL in various documentation and source code files. The changes ensure consistency in the project's references to its GitHub repository.

[docs] Change DeciMojo in URLs to lowercase

---

src/decimojo/arithmetics.mojo
src/decimojo/decimal.mojo
src/decimojo/utility.mojo

This pull request fixes a bug in `multiply()` due to implicit type conversion. More specifically, ```UInt128(a) * 10 ** 28``` would implicitly convert the value into Int. Thus, all "power to 10" are replaced by the function `power_of_10()`.

[fix] Fix bug in `multiply()` due to implicit type conversion

---

benches/bench.mojo
benches/bench_log10.mojo
mojoproject.toml
src/decimojo/__init__.mojo
src/decimojo/decimal.mojo
src/decimojo/exponential.mojo
tests/test_log.mojo
tests/test_log10.mojo

This pull request includes the `log` and `log10` functions in the `decimojo` library.
It also introduces a new benchmark for the `log10` function and includes several updates to the `Decimal` struct in the `decimojo` library.
* Included `log` and `log10` in the `decimojo` library's `__init__.mojo` file to make them available for import.
* Added a comprehensive benchmark for the `log10` function in `benches/bench_log10.mojo` to compare performance against Python's decimal module with diverse test cases.
* Updated `benches/bench.mojo` to include `bench_log10` in the list of benchmarks.
* Updated `mojoproject.toml` to include `test_log` and `test_log10` in the test configurations and `bench_log10` in the benchmark configurations.
* Added `@always_inline` decorator to several static methods …

[decimal] Implement the `log()` and the `log10()` functions

---

benches/bench.mojo
benches/bench_quantize.mojo
mojoproject.toml
src/decimojo/__init__.mojo
src/decimojo/decimal.mojo
src/decimojo/rounding.mojo
tests/test_quantize.mojo

This pull request adds support for a new `quantize` function across various files and updates dependencies. The most important changes include the addition of the `quantize` function, updates to the `mojoproject.toml` file, and the inclusion of new benchmarks and tests.
* `src/decimojo/decimal.mojo`: Added the `quantize` method to the `Decimal` struct to allow quantizing a `Decimal` to a specified exponent.
* `src/decimojo/rounding.mojo`: Implemented the `quantize` function, which rounds a value according to the exponent of the second operand.
* `mojoproject.toml`: Added the `max` dependency and included `test_quantize` and `bench_quantize` tasks.
* `benches/bench.mojo`: Added `bench_quantize` to the list of benchmarks.
* `src/decimojo/__init__.mojo`: Updated imports to include the new …

[decimal] Implement the `quantize()` function

---

README.md

This pull request includes several updates to the `README.md` file for the DeciMojo library. The changes focus on improving clarity, updating examples, and correcting some inaccuracies in the documentation.
Documentation improvements:
* Revised the overview section to enhance clarity and readability.
* Updated the installation instructions to streamline the process and improve formatting.
Example corrections:
* Corrected the division and mathematical function results in the examples.
* Corrected the example for checking if a decimal is an integer.

[docs] Update the readme file

---

src/decimojo/bigint/bigint.mojo
tests/bigint/test_bigint_to_int.mojo

This pull request includes several changes to the `BigInt` structure in the `src/decimojo/bigint/bigint.mojo` file to improve its functionality and add new initialization methods. Additionally, new tests have been added to validate these changes.
Enhancements to `BigInt` structure:
* `src/decimojo/bigint/bigint.mojo`: Added new initialization methods for `BigInt` including `__init__` with different parameter signatures and the `to_int` method for converting `BigInt` to `Int`. Updated the `from_components` method to `from_raw_words` and improved documentation and examples.
New tests:
* `tests/bigint/test_bigint_to_int.mojo`: Added new tests to validate the `to_int` method and `__int__` operator for various numerical cases, including edge cases and error scenarios.

[bigint] Add `to_int` and improve `from_int`

---

src/decimojo/bigint/arithmetics.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/str.mojo

This pull request includes several changes to the `decimojo` package, specifically focusing on improving the `BigInt` arithmetic operations and parsing of numeric strings. The most important changes include the introduction of a new method to check if a `BigInt` is zero, replacing string-based coefficients with list-based coefficients, and adding new augmented arithmetic assignment methods.
Improvements to `BigInt` arithmetic operations:
* `src/decimojo/bigint/arithmetics.mojo`: Introduced the `is_zero` method to simplify zero-checks in the `add` function.
* `src/decimojo/bigint/arithmetics.mojo`: Corrected the return statements in the `add`, `subtract`, and `negative` functions to properly return the result.
* `src/decimojo/bigint/arithmetics.mojo`: Simplified the `absolute` function by …

[bigint] Optimize parsing of numeric strings

---

src/decimojo/bigint/arithmetics.mojo
src/decimojo/bigint/bigint.mojo
tests/bigint/test_bigint_multiply.mojo

This pull request focuses on enhancing the `BigInt` type in the `decimojo` library by adding multiplication functionality and comprehensive tests. The most important changes include the addition of the `multiply` function, modifications to the `BigInt` structure to support the new functionality, and the creation of extensive tests to ensure the correctness of the multiplication operation.
* Added the `multiply` function to perform multiplication of two `BigInt` numbers in `src/decimojo/bigint/arithmetics.mojo`.
* Introduced the `__mul__` and `__imul__` methods to the `BigInt` structure to support the multiplication operator.
* Replaced the alias `_words_type` with `List[UInt32]` for the `words` field in the `BigInt` structure.
* Updated the `__init__` methods to use `List[UInt32]` …

[bigint] Implement `multiply` for `BigInt`

---

README.md
benches/biguint/bench.mojo
benches/biguint/bench_biguint_truncate_divide.mojo
mojoproject.toml
src/decimojo/__init__.mojo
src/decimojo/biguint/__init__.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/biguint/comparison.mojo
tests/biguint/test_biguint_arithmetics.mojo
tests/biguint/test_biguint_truncate_divide.mojo

This pull request includes several notable updates to the `DeciMojo` library, focusing on expanding its functionality and improving its documentation. Key changes involve the addition of a new type `BigUInt`, updated documentation, and new tests for the `BigUInt` type.
* `README.md`: Updated to reflect the inclusion of `BigInt` and the ongoing development of `BigDecimal`. Added a quick start guide for `BigInt`.
* `src/decimojo/__init__.mojo`: Added imports for `BigInt` and `BigUInt` types.
* `benches/biguint/bench.mojo`: Added a new benchmark for `BigUInt` truncate divide.
* `mojoproject.toml`: Added a new benchmark command for `BigUInt`.
* `src/decimojo/biguint/__init__.mojo`: Created a new sub-package for big unsigned integer arithmetic.
* `src/decimojo/biguint/comparison.mojo`: …

[integer] Implement `BigUInt`, basic methods and arithmetic functions

---

README.md
benches/biguint/bench.mojo
benches/biguint/bench_biguint_add.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo

This pull request includes several changes to the `DeciMojo` library, focusing on improving the `BigUInt` type and its arithmetic operations. The most important changes involve refactoring methods for better performance and clarity, and updating documentation.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L14-R14): Updated the description of `BigInt` to specify that it is a base-10 arbitrary-precision integer type. Added a detailed explanation of the nomenclature and the design philosophy behind `DeciMojo`. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L14-R14) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R140-R146)
* …

[integer] Optimize `BigUInt` type and its arithmetic operations

---

README.md
benches/biguint/bench.mojo
benches/biguint/bench_biguint_multiply.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/biguint/comparison.mojo

This pull request introduces several enhancements and new features to the `decimojo` library, focusing on arithmetic operations, comparison functions, and benchmarking. The most important changes are the addition of the Toom-Cook 3-way multiplication algorithm, new power and comparison methods for the `BigUInt` structure, and updates to the benchmarking script.
* [`src/decimojo/biguint/arithmetics.mojo`](diffhunk://#diff-95a5c66e5957fff2a2a8a2710ffb11a4ad7d0bddaf3bc11d075d62ddaa8b915cR404-R548): Added the `multiply_toom_cook_3` function, implementing the Toom-Cook 3-way multiplication algorithm for efficient large number multiplication.
* [`src/decimojo/biguint/biguint.mojo`](diffhunk://#diff-f9432b9b2671643af91201f9e3f011551a3d3b0e6d7b256d0d4569f5ae59848aR581-R623): Introduced `__pow__` …

[integer] Implement several dunder methods for `BigUInt`

---

mojoproject.toml

This pull request includes changes to the `mojoproject.toml` file, focusing on updating project metadata and dependencies.
Project metadata updates:
* Updated the project description to "A comprehensive decimal and integer mathematics library for Mojo" from "A fixed-point decimal arithmetic library written in Mojo 🔥".
* Commented out the nightly channel URL in the `channels` list, simplifying the active channels to "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", and "conda-forge".
Dependency updates:
* Modified the version constraint for the `max` dependency to ">=25.2" from ">=25.2,<25.3".

[max] Update max version to 25.2

---

benches/bigint/bench.mojo
benches/bigint/bench_bigint_multiply.mojo
benches/biguint/bench.mojo
src/decimojo/bigint/arithmetics.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/bigint/comparison.mojo
src/decimojo/biguint/biguint.mojo

This pull request includes significant changes to the `BigInt` and `BigUInt` benchmarks and arithmetic operations. The changes improve the initialization and handling of `BigInt` objects, update the benchmarks to use more descriptive commands, and enhance the comparison operations. Below are the most important changes:
* [`benches/bigint/bench.mojo`](diffhunk://#diff-2a97f8dc8465f7a88d361dcee4dcb3020bd75f18a3a189e817fb9af8996bbb75R2): Added the import for `bench_bigint_multiply` and updated the command options to use descriptive strings instead of numbers. [[1]](diffhunk://#diff-2a97f8dc8465f7a88d361dcee4dcb3020bd75f18a3a189e817fb9af8996bbb75R2) [[2]](diffhunk://#diff-2a97f8dc8465f7a88d361dcee4dcb3020bd75f18a3a189e817fb9af8996bbb75L12-R36)
* …

[integer] Enhance the comparison operations of `BigInt`

---

src/decimojo/bigint/arithmetics.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/bigint/comparison.mojo
src/decimojo/biguint/biguint.mojo
tests/bigint/test_bigint_truncate_divide.mojo

This pull request includes several changes to the `BigInt` and `BigUInt` structures in the `decimojo` library. The most important changes involve adding new methods, renaming and refactoring existing methods, and updating internal representation functions.
* Added `__pow__` methods to handle exponentiation with both `Self` and `Int` types and the corresponding `power` methods for internal calculations. [[1]](diffhunk://#diff-d65a756a58e3387a2b30bbe88308c3b318d71d2116b2870ac0a44109729e554bR445-R452) [[2]](diffhunk://#diff-d65a756a58e3387a2b30bbe88308c3b318d71d2116b2870ac0a44109729e554bR547-R579)
* Renamed `compare_absolute` to `compare_magnitudes` and reintroduced the `compare` method. [[1]](diffhunk://#diff-d65a756a58e3387a2b30bbe88308c3b318d71d2116b2870ac0a44109729e554bL511-L524) …

[integer] Re-write arithmetic functions of `BigInt` by using `BigUInt`'s methods

---

.github/workflows/run_tests.yaml
README.md
mojoproject.toml
src/decimojo/__init__.mojo
src/decimojo/tests.mojo
src/tomlmojo/__init__.mojo
src/tomlmojo/parser.mojo
src/tomlmojo/tokenizer.mojo
tests/biguint/test_biguint_arithmetics.mojo
tests/biguint/test_biguint_truncate_divide.mojo
tests/biguint/test_data/biguint_arithmetics.toml
tests/biguint/test_data/biguint_truncate_divide.toml

This pull request includes several changes to improve the testing and packaging of the `decimojo` and `tomlmojo` libraries. The most important changes involve implementing a TOML parser in package `tomlmojo`, restructuring the test cases to load from a TOML file, adding new test cases, and updating the packaging commands.
Improvements to testing:
* [`tests/biguint/test_biguint_arithmetics.mojo`](diffhunk://#diff-855e834af415ace9cb8340506c824c86a99bed282917f2d90075705170195827R7-R52): Refactored the test functions (`test_add`, `test_subtract`, `test_multiply`, `test_extreme_cases`) to load test cases from a TOML file and added structured `TestCase` for better test management. [[1]](diffhunk://#diff-855e834af415ace9cb8340506c824c86a99bed282917f2d90075705170195827R7-R52) …

[toml] Implement a TOML parser as package `tomlmojo` and use it to re-factor tests

---

benches/bigint/bench.mojo
benches/biguint/bench.mojo
benches/biguint/bench_biguint_from_string.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/prelude.mojo
src/decimojo/rounding_mode.mojo
src/decimojo/utility.mojo

This pull request includes several changes to improve the functionality and performance of the BigUInt and BigInt benchmarks and arithmetic operations. The most important changes include adding a new benchmark for the BigUInt `from_string` constructor, modifying arithmetic functions to use a more efficient approach for handling word lists, and making adjustments to the BigInt initialization.
* [`benches/biguint/bench_biguint_from_string.mojo`](diffhunk://#diff-87d18d79958722c0493a39cc0e6207042479e37a8af822e6436b18b4b2f46ad1R1-R372): Added a comprehensive benchmark for the BigUInt `from_string` constructor, comparing its performance against Python's built-in `int()` constructor with 20 diverse test cases.
* `benches/bigint/bench.mojo` and `benches/biguint/bench.mojo`: Updated the input …

[integer] Refine the constructors of `BigUInt`

---

src/decimojo/__init__.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/biguint/biguint.mojo

This pull request introduces significant changes to the `decimojo` library, primarily focusing on the addition of the `BigDecimal` type and various improvements to the `BigInt` and `BigUInt` types. The changes include new functionality, refactoring, and code cleanup.
* **BigDecimal Implementation**:
* Added a new `BigDecimal` type with comprehensive methods for construction, arithmetic operations, and type conversion. (`src/decimojo/bigdecimal/bigdecimal.mojo`)
* **BigInt Enhancements**:
* Refactored `BigInt` to handle the case of `Int.MIN` more robustly by introducing an `is_min` flag. (`src/decimojo/bigint/bigint.mojo`) [[1]](diffhunk://#diff-d65a756a58e3387a2b30bbe88308c3b318d71d2116b2870ac0a44109729e554bR218-R225) [[2]](diffhunk://#diff-d65a756a58e3387a2b30bbe88308c3b318d71d2116b2870ac …

[decimal] Implement some IO methods for `BigDecimal`

---

benches/bigdecimal/bench.mojo
benches/bigdecimal/bench_bigdecimal_subtract.mojo
mojoproject.toml
src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/biguint/arithmetics.mojo

This pull request includes several changes to the `benches/bigdecimal/bench.mojo`, `mojoproject.toml`, and `src/decimojo/bigdecimal/arithmetics.mojo` files to add new functionality and improve the codebase. The most important changes include adding a new subtraction benchmark, renaming benchmark commands, and implementing a subtraction function for `BigDecimal`.
* Added a new subtraction benchmark by importing `bench_bigdecimal_subtract` and updating the benchmark commands in `benches/bigdecimal/bench.mojo`. [[1]](diffhunk://#diff-96175f1000f81fe074f70a9adc4b39cd3f2dac8e85d30aa7efed9fc02b46e5ecR2) [[2]](diffhunk://#diff-96175f1000f81fe074f70a9adc4b39cd3f2dac8e85d30aa7efed9fc02b46e5ecR12) [[3]](diffhunk://#diff-96175f1000f81fe074f70a9adc4b39cd3f2dac8e85d30aa7efed9fc02b46e5ecR21-R25)
* …

[decimal] Implement a subtraction function for `BigDecimal`

---

mojoproject.toml
tests/bigdecimal/test_bigdecimal_arithmetics.mojo
tests/bigdecimal/test_data/bigdecimal_arithmetics.toml

This pull request introduces several significant changes to the `mojoproject.toml` and `tests/bigdecimal` files, primarily adding new functionality for testing BigDecimal subtraction. The most important changes include the addition of a new test function for BigDecimal subtraction, updates to the test data, and minor modifications to existing commands.
* [`tests/bigdecimal/test_bigdecimal_arithmetics.mojo`](diffhunk://#diff-072ed46a8bb09c6e6a52a3d5466019af8860ed562fcc12e8a52dfca16a21a8bfR88-R163): Added a new function `test_subtract()` to test BigDecimal subtraction with various test cases. This includes loading test cases from a TOML file, running the tests, and validating the results.
* [`tests/bigdecimal/test_data/bigdecimal_arithmetics.toml`](diffhunk://#diff-4544caef0a863355612643e4ce …

[decimal] Add tests for `subtract()` of `BigDecimal`

---

benches/bigdecimal/bench.mojo
benches/bigdecimal/bench_bigdecimal_divide.mojo
src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
tests/bigdecimal/test_bigdecimal_divide.mojo
tests/bigdecimal/test_data/bigdecimal_divide.toml

This pull request includes significant changes to the BigInt and BigDecimal arithmetic operations, introducing new functionality and improving existing methods. The most important changes include adding true division functionality for BigDecimal, modifying scaling methods, and updating the handling of leading zeros in BigUInt operations.
Notably, this PR fixes a bug in `BigUInt.multiply` where the carry is mistakenly skipped if a word of x2 is zero.
* Added `true_divide` function to perform division with specified precision and rounding rules in `src/decimojo/bigdecimal/arithmetics.mojo`.
* Updated the benchmarks to include the new division operation in `benches/bigdecimal/bench.mojo`. [[1]](diffhunk://#diff-96175f1000f81fe074f70a9adc4b39cd3f2dac8e85d30aa7efed9fc02b46e5ecR4) …

[decimal] Implement `true_divide` for `BigDecimal` type + fix a bug in `BigUInt.multiply`

---

benches/bigdecimal/bench.mojo
benches/bigdecimal/bench_bigdecimal_scale_up_by_power_of_10.mojo
benches/bigdecimal/bench_scale_up_by_power_of_10.mojo
src/decimojo/__init__.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/comparison.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/rounding_mode.mojo
tests/bigdecimal/test_bigdecimal_compare.mojo
tests/bigdecimal/test_data/bigdecimal_compare.toml

This pull request introduces a new benchmark for scaling up BigUInt values by powers of 10 and includes various improvements and additions to the `BigDecimal` class. The most important changes include adding a new benchmark file, updating the main benchmark script to include the new benchmark, and enhancing the `BigDecimal` class with new methods.
* Added `bench_bigdecimal_scale_up_by_power_of_10.mojo` to benchmark the `scale_up_by_power_of_10` function for `BigUInt` values.
* Updated `benches/bigdecimal/bench.mojo` to include the new benchmark for scaling up by powers of 10. [[1]](diffhunk://#diff-96175f1000f81fe074f70a9adc4b39cd3f2dac8e85d30aa7efed9fc02b46e5ecR5) [[2]](diffhunk://#diff-96175f1000f81fe074f70a9adc4b39cd3f2dac8e85d30aa7efed9fc02b46e5ecR21-R22) …

[decimal][integer] Implement comparison operators for `BigDecimal` + Improve `BigUInt.scale_up_by_power_of_10()`

---

README.md
benches/bigdecimal/bench.mojo
benches/bigdecimal/bench_bigdecimal_sqrt.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/exponential.mojo
src/decimojo/decimal/exponential.mojo
src/decimojo/utility.mojo
tests/bigdecimal/test_bigdecimal_exponential.mojo
tests/bigdecimal/test_data/bigdecimal_exponential.toml

This pull request introduces several enhancements to the `BigDecimal` type in the DeciMojo library, including the addition of square root functionality and related tests. The most important changes include updates to the `BigDecimal` struct, new exponential functions, and corresponding unit tests.
Enhancements to `BigDecimal` type:
* [`src/decimojo/bigdecimal/bigdecimal.mojo`](diffhunk://#diff-be2f9b2702fd15952546e17fe94a64c22902a0e4678bfd9cb925269647923db4R544-R553): Added `sqrt` method to compute the square root of a `BigDecimal` number with a specified precision, and an `is_negative` method to check if a number is negative. [[1]](diffhunk://#diff-be2f9b2702fd15952546e17fe94a64c22902a0e4678bfd9cb925269647923db4R544-R553) [[2]](diffhunk://#diff-be2f9b2702fd15952546e17fe94a64c22902a0e4678b …

[decimal] Implement `sqrt` for `BigDecimal`

---

README.md
benches/bigdecimal/bench.mojo
benches/bigdecimal/bench_bigdecimal_exp.mojo
docs/todo.md
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/exponential.mojo
src/decimojo/bigdecimal/rounding.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo

This pull request includes several updates to the `DeciMojo` project, focusing on enhancing the documentation, adding new functionality, and improving performance. The most important changes are summarized below:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R16): Updated table of contents and added `` comments to headings to improve navigation and readability. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R16) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L171-R189) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L189-R199) [[4]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L205 …

[decimal] Implement `exp()` for `BigDecimal`

---

benches/bigdecimal/bench_bigdecimal_exp.mojo
benches/bigdecimal/bench_bigdecimal_sqrt.mojo
src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/exponential.mojo

This pull request includes several updates to the BigDecimal library, focusing on improving the precision and performance of mathematical operations. The changes involve modifying benchmarks, adding new functions, and optimizing existing ones.
* Updated benchmark cases in `benches/bigdecimal/bench_bigdecimal_exp.mojo` to use more realistic values for the exponential function tests. [[1]](diffhunk://#diff-e1fde1daccb3f0113cd71bc255dd67f6e65ed4338dbba83685ee2b965591623dL560-R563) [[2]](diffhunk://#diff-e1fde1daccb3f0113cd71bc255dd67f6e65ed4338dbba83685ee2b965591623dL578-R581) [[3]](diffhunk://#diff-e1fde1daccb3f0113cd71bc255dd67f6e65ed4338dbba83685ee2b965591623dL596-R599) [[4]](diffhunk://#diff-e1fde1daccb3f0113cd71bc255dd67f6e65ed4338dbba83685ee2b965591623dL614-R617)
* Increased the number …

[decimal] Optimize `exp` for `BigDecimal`

---

docs/internal_notes.md
src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/exponential.mojo
src/decimojo/biguint/biguint.mojo

This pull request includes several updates to the `BigDecimal` and related arithmetic operations in the `decimojo` library. The changes primarily focus on adding new mathematical functions, optimizing existing methods, and improving precision handling.
* Added `power`, `log`, and `log10` functions to `BigDecimal` for exponentiation and logarithmic calculations. (`src/decimojo/bigdecimal/bigdecimal.mojo`, `src/decimojo/bigdecimal/exponential.mojo`) [[1]](diffhunk://#diff-be2f9b2702fd15952546e17fe94a64c22902a0e4678bfd9cb925269647923db4L462-R471) [[2]](diffhunk://#diff-8edc842002d08323642db57f775ff7f626be068d55cb55bbe637e215f68ed8bcL30-R172) [[3]](diffhunk://#diff-8edc842002d08323642db57f775ff7f626be068d55cb55bbe637e215f68ed8bcR592-R701)
* Introduced `is_integer` and `is_odd` methods to …

[decimal] Implement `power` function for `BigDecimal`

---

README.md
mojoproject.toml
src/decimojo/decimal/arithmetics.mojo
src/decimojo/decimal/comparison.mojo
src/decimojo/decimal/constants.mojo
src/decimojo/decimal/decimal.mojo
src/decimojo/decimal/rounding.mojo
src/decimojo/decimal/special.mojo

This pull request involves several updates to the `DeciMojo` project, mainly focusing on changing the description of the library from a "comprehensive" to an "arbitrary-precision" mathematics library and removing redundant header comments from source files.
Description updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L3-R3): Updated the description to "an arbitrary-precision decimal and integer mathematics library for Mojo" and adjusted related text to reflect this change. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L3-R3) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L19-L25) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf8742 …

[docs] Update descriptions and examples

---

benches/bigdecimal/bench.mojo
benches/bigdecimal/bench_bigdecimal_root.mojo
benches/bigdecimal/bench_bigdecimal_sqrt.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/exponential.mojo
tests/bigdecimal/test_bigdecimal_exponential.mojo

This pull request introduces a new root function for the BigDecimal library and makes several updates to the benchmarking and testing code to support this new functionality. Additionally, some improvements and optimizations have been made to existing functions.
Key changes include:
* Added a new `root` function to the `BigDecimal` struct for calculating the nth root of a BigDecimal number.
* Introduced `integer_root` and `is_integer_reciprocal_and_return` helper functions in `exponential.mojo` to support the new root calculation.
* Updated `benches/bigdecimal/bench.mojo` to include the new `root` benchmark, adding the necessary imports, command handling, and execution logic. [[1]](diffhunk://#diff-96175f1000f81fe074f70a9adc4b39cd3f2dac8e85d30aa7efed9fc02b46e5ecR8) …

[decimal] Implement `root()` for `BigDecimal`

---

src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/exponential.mojo
src/decimojo/bigdecimal/rounding.mojo
tests/bigdecimal/test_bigdecimal_exponential.mojo
tests/bigdecimal/test_data/bigdecimal_exponential.toml

This pull request includes changes to the `decimojo` library, primarily focusing on the `BigDecimal` struct and its associated functions. The most significant changes involve adding a new parameter, `fill_zeros_to_precision`, to various functions to enhance the precision handling of `BigDecimal` operations. Additionally, the test suite has been updated to accommodate these changes.
Enhancements to `BigDecimal` precision handling:
* [`src/decimojo/bigdecimal/bigdecimal.mojo`](diffhunk://#diff-be2f9b2702fd15952546e17fe94a64c22902a0e4678bfd9cb925269647923db4R625-R635): Added `fill_zeros_to_precision` parameter to the `round_to_precision` method in the `BigDecimal` struct.
* [`src/decimojo/bigdecimal/exponential.mojo`](diffhunk://#diff-8edc842002d08323642db57f775ff7f626be068d55cb55bbe637e215f6 …

[decimal][tests] Add tests for `root()` and `power()` of `BigDecimal`

---

README.md
benches/bigdecimal/bench.mojo
benches/bigdecimal/bench_bigdecimal_round.mojo
src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/comparison.mojo
src/decimojo/bigdecimal/rounding.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/rounding_mode.mojo
tests/bigdecimal/test_bigdecimal_rounding.mojo
tests/bigdecimal/test_data/bigdecimal_rounding.toml

This pull request includes several changes to the BigDecimal library, focusing on adding new functionalities, improving existing methods, and making the code more robust. The most important changes include the addition of new arithmetic operations, enhancements to rounding and comparison methods, and updates to the benchmarking script.
* Added `truncate_divide` and `truncate_modulo` functions to `src/decimojo/bigdecimal/arithmetics.mojo` for performing truncated division and modulo operations.
* Implemented `__floordiv__` and `truncate_divide` methods in the `BigDecimal` struct to support floor division. [[1]](diffhunk://#diff-be2f9b2702fd15952546e17fe94a64c22902a0e4678bfd9cb925269647923db4R466-R472) [[2]](diffhunk://#diff-be2f9b2702fd15952546e17fe94a64c22902a0e4678bfd9cb925269647923db4R65 …

[decimal] Implement `round()` for `BigDecimal`

---

mojoproject.toml
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/exponential.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/decimal/arithmetics.mojo
src/decimojo/decimal/decimal.mojo
src/decimojo/decimal/special.mojo
src/decimojo/prelude.mojo
src/decimojo/str.mojo
src/decimojo/utility.mojo
src/tomlmojo/tokenizer.mojo
tests/bigdecimal/test_bigdecimal_divide.mojo
tests/bigdecimal/test_bigdecimal_exponential.mojo
tests/bigint/test_bigint_floor_divide.mojo
tests/bigint/test_bigint_truncate_divide.mojo
tests/decimal/test_ln.mojo

Update the code to accommodate with Mojo 25.3

[mojo] Update the code to accommodate with Mojo 25.3

---

README.md
docs/changelog.md
docs/changelog_unreleased.md
docs/readme_zht.md
pixi.toml
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigint/arithmetics.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/biguint/biguint.mojo

This pull request introduces multiple changes across the `DeciMojo` library to enhance functionality, improve performance, and update documentation. Key updates include support for implicit type conversion between built-in integral types and arbitrary-precision types, optimizations for `BigInt` operations, and bug fixes for `BigDecimal`. Additionally, version updates and documentation refinements are included.

[integer][decimal][docs] Improve type conversions + optimize `iadd` for `BigInt` + Update documentation

---

docs/internal_notes.md
src/decimojo/bigdecimal/constants.mojo

This pull request introduces significant improvements to the `BigDecimal` library by optimizing the calculation of π (pi) for high precision and documenting the performance characteristics of different algorithms. The main changes include replacing Machin's formula with the Chudnovsky algorithm for faster computation, introducing binary splitting for efficiency, and adding internal notes on time complexity and algorithm results.
* [`src/decimojo/bigdecimal/constants.mojo`](diffhunk://#diff-41cd4654562f4a78c9b73f60941a2f1e1d8509a3dc8a93469408e4a5456619f2R154-R289): Replaced Machin's formula with the Chudnovsky algorithm for π calculation, leveraging binary splitting for higher precision and faster computation. Added caching logic to store precomputed values for precision ≤ 1024.
* …

[decimal] Use Chudnovsky with binary splitting to calculate pi

---

benches/biguint/bench_biguint_multiply.mojo
benches/biguint/bench_biguint_multiply_complexity.mojo
docs/changelog.md
docs/internal_notes.md
pixi.toml
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/biguint/comparison.mojo

This pull request introduces enhancements multiplication of `BigUInt` by implementing the Karatsuba algorithm.
* Implement Karatsuba algorithm for multiplication.
* Implement slices addition and multiplication.
* [`src/decimojo/biguint/biguint.mojo`](diffhunk://#diff-f9432b9b2671643af91201f9e3f011551a3d3b0e6d7b256d0d4569f5ae59848aR1065-R1074): Added a new method `scale_up_by_power_of_billion` to efficiently scale a `BigUInt` in-place by powers of a billion, enabling faster operations for specific use cases.
* Removed the `raises` keyword from the `__iadd__` method as it no longer throws exceptions.
* [`benches/biguint/bench_biguint_multiply.mojo`](diffhunk://#diff-3fba3fe441d30e17e77d7e18b33b2508452b08f07e7af177d413c08b5b5c88c2L451-R453): Added benchmarks for new cases involving extremely …

[integer] Improve `BigUInt` multiplication by implementing Karatsuba algorithm

---

README.md
benches/biguint/bench.mojo
benches/biguint/bench_biguint_divide_complexity.mojo
benches/biguint/bench_biguint_truncate_divide.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo

Refine the arithmetic functions for `BigUInt`
1. Add `subtract_inplace()`
2. Optimize the cases when the second argument is one-word long.
3. Refine the estimation of quotient for division using 3-by-2 division.
4. Update the function `is_one()` and `is_two`.
5. Remove unused function `floor_divide_partition()`.

[integer] Refine arithmetic functions of `BigUInt`

---

src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo

This pull request focuses on optimizing arithmetic operations for `BigUInt` in the `decimojo` library. The changes primarily involve replacing hardcoded constants (e.g., `1_000_000_000`) with the `BigUInt.BASE` and `BigUInt.BASE_MAX` properties, introducing in-place scaling methods, and improving normalization logic for division operations. These updates enhance code maintainability, readability, and performance.
* Enhanced normalization logic in `floor_divide` by introducing a table-based lookup for determining the number of digits to shift, improving quotient estimation accuracy. (`[src/decimojo/biguint/arithmetics.mojoL931-R1037](diffhunk://#diff-95a5c66e5957fff2a2a8a2710ffb11a4ad7d0bddaf3bc11d075d62ddaa8b915cL931-R1037)`)
* Although no correction is expected to occur, still kept the …

[integer] Refine normalization of `BigUInt` division so that correction is no longer needed

---

benches/biguint/bench_biguint_add.mojo
benches/biguint/bench_biguint_multiply.mojo
benches/biguint/bench_biguint_multiply_complexity.mojo
src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/bigdecimal/comparison.mojo
src/decimojo/bigdecimal/exponential.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo

This pull request introduces significant updates to the `bench_biguint` benchmarking suite, optimizes arithmetic operations in the `BigUInt` and `BigDecimal` modules, and refactors method names for clarity and consistency. Additionally, new benchmarking cases and constants are added to improve performance testing and support for larger numbers.
1. Use SIMD to accelerate BigUInt addition and in-place addition. The speed gain is 2x to 4x for large numbers.
2. Refine the BigUInt subtraction and in-place addition with some tricks on carry so that floor_divide and modulo are replaced by addition and subtraction.
3. Use a trick to first do a paralelled addition word-by-word, and then do normalized carries with one loop.
* [`src/decimojo/bigdecimal/arithmetics.mojo`](diffhunk://#diff-f79534f4e7fd …

[integer] Optimize `BigUInt` addition and subtraction with SIMD and early stop tricks

---

src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/bigdecimal/exponential.mojo
src/decimojo/biguint/arithmetics.mojo

This pull request introduces several enhancements and modifications to the `BigUInt` and `BigDecimal` arithmetic operations. Key changes include the introduction of optimized carry normalization methods, improvements to division algorithms, and the addition of a specialized multiplication function for small values. These changes aim to improve performance, readability, and maintainability of the codebase.
* Renamed and refactored `normalize_carries` to `normalize_carries_lt_2_bases` and introduced `normalize_carries_lt_4_bases` for handling specific ranges of word values during arithmetic operations. These methods ensure efficient normalization of carries based on the range of input values. [[1]](diffhunk://#diff-95a5c66e5957fff2a2a8a2710ffb11a4ad7d0bddaf3bc11d075d62ddaa8b915cL69-R70) …

[integer] Update `multiply_inplace_by_uint32()` for `BigUInt` when the y is no greater than 4

---

pixi.toml
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/bigdecimal/constants.mojo
src/decimojo/bigint/arithmetics.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/biguint/comparison.mojo
src/decimojo/biguint/exponential.mojo
src/decimojo/decimal128/decimal128.mojo
src/decimojo/decimal128/utility.mojo
src/decimojo/errors.mojo
src/decimojo/tests.mojo
src/tomlmojo/parser.mojo
src/tomlmojo/tokenizer.mojo

This pull request updates the codebase to Mojo v25.5 (nightly).
* Updated the `pixi.toml` file to increment the version from `0.4.1` to `0.5.0`, switch the `max` dependency to a more flexible version constraint (`>25.4`), and include the `max-nightly` channel in the `channels` list.
* Added new traits (`AnyType`, `Copyable`, `Movable`, `Representable`) to the `BigDecimal` struct to enhance compatibility and functionality.
* Updated various methods in `BigDecimal` to use `Self` instead of `BigDecimal`, improving type consistency and reducing redundancy. This includes methods like `extend_precision`, `normalize`, and comparison operators (`__gt__`, `__lt__`, etc.).
* Added new traits (`AnyType`, `Comparable`, `Copyable`, `Movable`) to the `BigInt` struct, aligning it with the enhancements …

[mojo] Update the codebase to Mojo v25.5 nightly

---

.gitattributes
pixi.toml
src/decimojo/bigint/arithmetics.mojo
src/decimojo/bigint/bigint.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/errors.mojo
src/tomlmojo/tokenizer.mojo

This pull request introduces significant improvements and error handling enhancements for arithmetic operations in the `BigInt` and `BigUInt` types. Key changes include the removal of the `raises` keyword from function signatures, the addition of structured error handling using custom error types, and improvements to the implementation of arithmetic operations to ensure correctness and maintainability.
* Introduced custom error types such as `DeciMojoError`, `OverflowError`, and `ZeroDivisionError` across the codebase for more structured and descriptive error reporting. For example, division and modulo operations now raise `ZeroDivisionError` when dividing by zero.
* Replaced generic error messages with detailed exceptions that include contextual information such as the file, function, …

[errors] Improve error handling by using `DeciMojoError` type

---

src/decimojo/bigdecimal/arithmetics.mojo
src/decimojo/biguint/arithmetics.mojo

This pull request introduces several updates to the `decimojo` library, focusing on improving numerical operations with `BigUInt` and `BigDecimal` types. Key changes include replacing a placeholder function with a more optimized implementation, adding debug assertions to enforce non-negative input constraints, and introducing a new utility function for division by powers of a billion.
* **Optimized division by powers of a billion**: Replaced the placeholder call to `floor_divide_by_power_of_ten` with the newly implemented `floor_divide_by_power_of_billion` in `true_divide_fast` for better performance.
* **New utility function**: Added `floor_divide_by_power_of_billion`, which efficiently removes the last `n` words of a `BigUInt`, equivalent to dividing by `(10^9)^n`. This function handles …

[integer] Implement `floor_divide_by_power_of_billion()`

---

.gitignore
README.md
src/decimojo/bigdecimal/bigdecimal.mojo
src/decimojo/biguint/arithmetics.mojo
src/decimojo/biguint/biguint.mojo
src/decimojo/biguint/comparison.mojo
src/decimojo/biguint/exponential.mojo
tests/biguint/test_biguint_arithmetics.mojo
tests/biguint/test_biguint_exponential.mojo

This pull request focuses on improving the `BigUInt` and `BigDecimal` implementations in the `decimojo` library by enhancing precision, optimizing arithmetic operations, and ensuring consistency in handling zero values. It also includes a minor documentation update. Below is a categorized summary of the most important changes:
* Update logic to ensure that there are no leading zero words in BigUInt by design. Add debug assert to check this.
* Update `is_zero()` and comparison functions given that there are no leading zero words in BigUInt by design.
* Fixed a syntax error in the `extend_precision` example in `BigDecimal` by correcting a missing closing quote.
* Replaced instances of `BigUInt()` with `BigUInt.ZERO` for clearer intent when representing zero values across multiple functions. …

[integer] Ensure that `BigUInt` has no leading zero words
